COLS_BELGE_SAYISI = ["Genelge"]
COLS_MADDE_SAYISI = ["Kanun", "Kanun Hükmünde Kararname", "Cumhurbaşkanlığı Kararnamesi",
                     "Tüzük", "Yönetmelik"]
COLS_MEVZUAT_NO = ["Kanun", "Kanun Hükmünde Kararname",
                     "Genelge", "Cumhurbaşkanlığı Kararnamesi",
                     "Tüzük", "Yönetmelik"]
COLS_REGA_TARIHI = ["Kanun", "Kanun Hükmünde Kararname","Resmi Gazete"
                      "Cumhurbaşkanlığı Kararnamesi",
                     "Tüzük", "Yönetmelik","Tebliğ"]
COLS_MEVZUAT_TARIHI = ["Kanun", "Kanun Hükmünde Kararname",
                     "Genelge", "Cumhurbaşkanlığı Kararnamesi",
                     "Tüzük", "Özelge"]
COLS_KURUM = ["Yönetmelik","Tebliğ"]
NAN_LABEL = "undefined"

KURUMLAR = [
            'Özelleştirme İdaresi Başkanlığı (öib)',
            'İstanbul Altın Borsası',
            'Kapadokya Alan Başkanlığı',
            'Telekomünikasyon İletişim Başkanlığı',
            'Türkiye Sermaye Piyasası Aracı Kuruluşları Birliği',
            'Türk Akreditasyon Kurumu (türkak)',
            'Türk Dişhekimleri Birliği (tdb)',
            'Şeker Kurumu',
            'Devlet Personel Başkanlığı',
            'Avrupa Birliği Eğitim ve Gençlik Programları Merkezi Başkanlığı',
            'Mali Suçları Araştırma Kurulu',
            'Çevre ve Orman Bakanlığı',
            'Türkiye Enerji, Nükleer ve Maden Araştırma Kurumu',
            'Çevre, Şehircilik ve İklim Değişikliği Bakanlığı',
            'Türkiye Bankalar Birliği',
            'Yüksek Seçim Kurulu Başkanlığı',
            'Aile ve Sosyal Hizmetler Bakanlığı',
            'Rekabet Kurumu (rk)',
            'Türk Patent ve Marka Kurumu',
            'Sigortacılık ve Özel Emeklilik Düzenleme ve Denetleme Kurumu',
            'Radyo ve Televizyon Üst Kurulu',
            'Rekabet Kurumu Başkanlığı',
            'Türkiye Odalar ve Borsalar Birliği (tobb)',
            'Tarım ve Kırsal Kalkınmayı Destekleme Kurumu (tkdk)',
            'Nükleer Düzenleme Kurumu',
            'Türkiye Elektrik İletim A.ş. (teiaş)',
            'Devlet Tiyatroları Genel Müdürlüğü (dt)',
            'Kişisel Verileri Koruma Kurumu',
            'Yargıtay',
            'Türkiye Bilimsel ve Teknolojik Araştırma Kurumu (tübitak)',
            'Devlet Hava Meydanları İşletmesi Genel Müdürlüğü',
            'Çay İşletmeleri Genel Müdürlüğü (çaykur)',
            'Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı (kosgeb)',
            'Türkiye Elektromekanik Sanayii A.ş. (temsan)',
            'Türkiye İstatistik Kurumu (tüik)',
            'Aile, Çalışma ve Sosyal Hizmetler Bakanlığı',
            'Türkiye Büyük Millet Meclisi',
            'Tta Gayrımenkul Anonım Şırketı Genel Müdürlüğü',
            'Türkiye Yazma Eserler Kurumu',
            'Türkiye Değerleme Uzmanları Birliği',
            'Kefalet Sandığı',
            'Türkiye İnsan Hakları Kurumu',
            'Anayasa Mahkemesi',
            'Kıyı Emniyeti Genel Müdürlüğü',
            'Toplu Konut İdaresi Başkanlığı',
            'Hakimler ve Savcılar Yüksek Kurulu',
            'Avrupa Birliği Bakanlığı',
            'Türkiye Elektrik Dağıtım A.ş. (tedaş)',
            'Özel Çevre Koruma Kurumu Başkanlığı',
            'Tasarruf Mevduatı Sigorta Fonu',
            'Sivil Havacılık Genel Müdürlüğü',
            'Türkiye Sağlık Enstitüleri Başkanlığı',
            'Türkiye Radyo-Televizyon Kurumu',
            'Bayındırlık ve İskan Bakanlığı',
            'Maden ve Petrol İşleri Genel Müdürlüğü',
            'Türkiye Cumhuriyeti Devlet Demiryolları (tcdd)',
            'Posta ve Telgraf Teşkilatı Genel Müdürlüğü (ptt)',
            'Makina ve Kimya Endüstrisi Kurumu (mkek)',
            'Milli Piyango İdaresi Genel Müdürlüğü (mp)',
            'Türkiye Serbest Muhasebeci Mali Müşavirler ve Yeminli Mali Müşavirler Odaları Birliği (türmob)',
            'Danıştay',
            'Hazine Müsteşarlığı',
            'Atatürk Kültür, Dil ve Tarih Yüksek Kurumu',
            'Kamu İhale Kurumu',
            'Devlet Su İşleri Genel Müdürlüğü (dsi)',
            'Türkiye Atom Enerjisi Kurumu (taek)',
            'Yurtdışı Türkler ve Akraba Topluluklar Başkanlığı',
            'Türk Patent Enstitüsü',
            'Tütün ve Alkol Piyasası Düzenleme Kurumu',
            'Kalkınma Bakanlığı',
            'Sayıştay',
            'Gençlik ve Spor Bakanlığı',
            'Türkiye Muhasebe Standartları Kurulu',
            'Vakıflar Genel Müdürlüğü',
            'Karayolları Genel Müdürlüğü (kgm)',
            'Türkiye İlaç ve Tıbbî Cihaz Kurumu',
            'Dışişleri Bakanlığı',
            'Türk Mühendis ve Mimar Odaları Birliği (tmmob)',
            'Para ve Kredi Koordinasyon Kurulu',
            'Spor Genel Müdürlüğü',
            'İstanbul Menkul Kıymetler Borsası (imkb)',
            'Bilgi Teknolojileri ve İletişim Kurumu',
            'Diyanet İşleri Başkanlığı',
            'Kamu Kurum Niteliğindeki Meslek Kuruluşları',
            'Sanayi ve Ticaret Bakanlığı',
            'Tarım ve Köy İşleri Bakanlığı',
            'Dış Ticaret Müsteşarlığı',
            'Aile ve Sosyal Politikalar Bakanlığı',
            'Cumhurbaşkanlığı',
            'Yükseköğretim Kurulu (yök)',
            ' Ulaştırma ve Altyapı Bakanlığı',
            'Başbakanlık',
            'Kültür ve Turizm Bakanlığı',
            'Bankacılık Düzenleme ve Denetleme Kurumu',
            'Enerji Piyasası Düzenleme Kurumu',
            'Milli Savunma Bakanlığı',
            'Kurum',
            'Orman ve Su İşleri Bakanlığı',
            'Enerji ve Tabii Kaynaklar Bakanlığı',
            'Milli Eğitim Bakanlığı',
            'Sanayi ve Teknoloji Bakanlığı',
            'Çalışma ve Sosyal Güvenlik Bakanlığı',
            'Sağlık Bakanlığı',
            'Türkiye Cumhuriyet Merkez Bankası',
            'Kamu Gözetimi, Muhasebe ve Denetim Standartları Kurumu',
            'Tarım ve Orman Bakanlığı',
            'Mesleki Yeterlilik Kurumu',
            'İçişleri Bakanlığı',
            'Adalet Bakanlığı',
            'Sermaye Piyasası Kurulu',
            'Ulaştırma, Denizcilik ve Haberleşme Bakanlığı',
            'Gümrük ve Ticaret Bakanlığı',
            'Hazine ve Maliye Bakanlığı',
            'Bilim, Sanayi ve Teknoloji Bakanlığı',
            'Tapu ve Kadastro Genel Müdürlüğü',
            'Çevre ve Şehircilik Bakanlığı',
            'Üniversite',
            'Gıda, Tarım ve Hayvancılık Bakanlığı',
            'Ticaret Bakanlığı',
            'Cumhurbaşkanlığı ',
            'Maliye Bakanlığı',
            'İstanbul Vergi Dairesi Başkanlığı',
            'Ekonomi Bakanlığı',
            'Bakanlar Kurulu',
            'Sosyal Güvenlik Kurumu',
            'T.C. Gelir İdaresi Başkanlığı'
             ]